<?php

namespace App\Services;

use App\Models\LoadDraft;

class LoadDraftScanMapper
{
    public function toScan(LoadDraft $draft): array
    {
        $draft->loadMissing(['consignee', 'warehouse']);
        $contact = is_array($draft->contact) ? $draft->contact : [];

        return [
            'isDocument' => true,
            'sender' => null,
            'receiver' => null,
            'customerCandidates' => [],
            'consigneeName' => (string) ($draft->consignee?->company_name ?: $draft->consignee?->name ?: ''),
            'consigneeTaxNumber' => (string) ($draft->consignee?->tax_number ?? ''),
            'consigneeCity' => (string) ($draft->consignee?->city ?? ''),
            'consigneeCountryCode' => (string) ($draft->consignee?->country_code ?? ''),
            'consignee' => $draft->consignee?->toArray(),
            'title' => (string) ($draft->title ?? ''),
            'transportType' => (string) ($draft->transport_type ?? ''),
            'storageTarget' => (string) ($draft->storage_target ?? ''),
            'warehouseId' => $draft->warehouse_id ? (int) $draft->warehouse_id : null,
            'warehouseName' => (string) ($draft->warehouse?->name ?? ''),
            'cargoType' => (string) ($draft->cargo_type ?? ''),
            'goodsType' => (string) ($draft->goods_type ?? ''),
            'hsSearchTerms' => '',
            'hsCodes' => $draft->hs_codes ?? [],
            'weightKg' => (float) ($draft->weight_kg ?? 0),
            'pallets' => (int) ($draft->pallets ?? 0),
            'bodyType' => (string) (($draft->body_types ?? [])[0] ?? ''),
            'lengthM' => (float) ($draft->length_m ?? 0),
            'widthM' => (float) ($draft->width_m ?? 0),
            'heightM' => (float) ($draft->height_m ?? 0),
            'volumeM3' => (float) ($draft->volume_m3 ?? 0),
            'vehicleType' => (string) ($draft->vehicle_type ?? ''),
            'loadingEquipment' => (string) (($draft->loading_methods ?? [])[0] ?? ''),
            'characteristics' => (string) (($draft->characteristics ?? [])[0] ?? ''),
            'specialRequirements' => $draft->special_requirements ?? [],
            'transportMode' => (string) ($draft->transport_mode ?? ''),
            'deliveryProof' => (string) ($draft->delivery_proof ?? ''),
            'requiresTracking' => (bool) $draft->must_be_trackable,
            'pickupCity' => (string) ($draft->pickup_city ?? ''),
            'pickupCountryCode' => (string) ($draft->pickup_country_code ?? ''),
            'pickupAddress' => (string) ($draft->pickup_address ?? ''),
            'pickupLatitude' => $draft->pickup_latitude !== null ? (float) $draft->pickup_latitude : null,
            'pickupLongitude' => $draft->pickup_longitude !== null ? (float) $draft->pickup_longitude : null,
            'pickupDate' => optional($draft->pickup_date)->format('Y-m-d') ?? '',
            'pickupDateTo' => optional($draft->pickup_date_to)->format('Y-m-d') ?? '',
            'pickupTimeFrom' => substr((string) ($draft->pickup_time_from ?? ''), 0, 5),
            'pickupTimeTo' => substr((string) ($draft->pickup_time_to ?? ''), 0, 5),
            'deliveryCity' => (string) ($draft->delivery_city ?? ''),
            'deliveryCountryCode' => (string) ($draft->delivery_country_code ?? ''),
            'deliveryAddress' => (string) ($draft->delivery_address ?? ''),
            'deliveryLatitude' => $draft->delivery_latitude !== null ? (float) $draft->delivery_latitude : null,
            'deliveryLongitude' => $draft->delivery_longitude !== null ? (float) $draft->delivery_longitude : null,
            'deliveryDate' => optional($draft->delivery_date)->format('Y-m-d') ?? '',
            'deliveryDateTo' => optional($draft->delivery_date_to)->format('Y-m-d') ?? '',
            'deliveryTimeFrom' => substr((string) ($draft->delivery_time_from ?? ''), 0, 5),
            'deliveryTimeTo' => substr((string) ($draft->delivery_time_to ?? ''), 0, 5),
            'currency' => (string) ($draft->currency ?? ''),
            'budget' => (float) ($draft->budget ?? 0),
            'priceTerms' => $draft->is_negotiable === null ? '' : ($draft->is_negotiable ? 'negotiable' : 'fixed'),
            'declaredValue' => (float) ($draft->declared_value ?? 0),
            'declaredValueCurrency' => (string) ($draft->shipment_value_currency ?? ''),
            'incoterm' => (string) ($draft->incoterms ?? ''),
            'paymentDueDays' => (int) ($draft->payment_due_days ?? 0),
            'temperatureMin' => $draft->temperature_min !== null ? (float) $draft->temperature_min : null,
            'temperatureMax' => $draft->temperature_max !== null ? (float) $draft->temperature_max : null,
            'requiresAdr' => (bool) $draft->requires_adr,
            'requiresTailLift' => (bool) $draft->requires_tail_lift,
            'tollRoadsIncluded' => (bool) $draft->toll_roads_included,
            'ferryIncluded' => (bool) $draft->ferry_included,
            'cmrRequired' => (bool) $draft->cmr_required,
            'palletExchangeRequired' => (bool) $draft->pallet_exchange_required,
            'customsRequired' => (bool) $draft->customs_required,
            'insuranceRequired' => (bool) $draft->insurance_required,
            'certificationRequired' => (bool) $draft->certification_required,
            'inspectionServicesRequired' => (bool) $draft->inspection_services_required,
            'isUrgent' => (bool) $draft->is_urgent,
            'contactName' => (string) ($contact['name'] ?? ''),
            'contactPhone' => (string) ($contact['phone'] ?? ''),
            'contactMobile' => (string) ($contact['mobile'] ?? ''),
            'contactFax' => (string) ($contact['fax'] ?? ''),
            'contactEmail' => (string) ($contact['email'] ?? ''),
            'bookingReference' => (string) ($draft->booking_reference ?? ''),
            'notes' => (string) ($draft->notes ?? ''),
            'customFields' => [],
            'confidence' => 1,
            'warnings' => [],
        ];
    }
}
